### ISSUE TITLE
Volume control has no effect

### ISSUE THREAD

**Issue by BishopT** [insin/vlc_remote#13]
_App version 1.1.1 installed from Google Play._

The volume slider has no effect on VLC volume. The issue seems to come from a wrong command sent to VLC. Requested URI is: `/requests/status.xml?command=volume&val=<float>` when [VLC wiki](https://wiki.videolan.org/VLC_HTTP_requests/) states:

``` ?command=volume&val=<val>
 Allowed values are of the form:
   +<int>, -<int>, <int> or <int>% 
```

See the screenshot of wireshark capture:
![vlc-remote-volume-control-float](https://user-images.githubusercontent.com/16278327/79117518-9d3a6f00-7d8b-11ea-886f-c3c1ab7f5ef0.png)

**Comment by insin** [comment]
This is working for me (on emulator and Android device) as is, but let's merge the PR and round it to an int anyway

![NCLAWSQ6av](https://user-images.githubusercontent.com/226692/80867165-fa17ae00-8cd5-11ea-9cbe-f76d952d35eb.gif)

**Comment by BishopT** [comment]
OK, thanks for feedback. Then I hope it's not hiding another problem. Will you be able to push an updated package on play store soon?

**Comment by BishopT** [comment]
ok, got the update, works like a charm now :+1:
