### ISSUE TITLE
control speed playback

### ISSUE THREAD

**Issue by frnandu** [insin/vlc_remote#22]
should give same fine control (increments of 0.1) just as pressing { and } on player,
most other apps don't allow for fine control, just x1.5
This would be great, thanks

**Comment by insin** [comment]
There's a `rate` command in the HTTP API we can use for this 👍

**Comment by insin** [comment]
Coming soon

![hAMcGTMadj](https://user-images.githubusercontent.com/226692/87854343-b0457800-c954-11ea-83a1-da800515c00f.gif)
