### ISSUE TITLE
Unable to change audio or subtitle track

### ISSUE THREAD

**Issue by DictationScratchPad** [insin/vlc_remote#25]
The buttons for selecting audio track and subtitle track are greyed out and do not function even if the video has multiple tracks for both.

![_20200621_210651](https://user-images.githubusercontent.com/50198630/85232902-29f44f80-b403-11ea-8901-6ad62c4cd477.JPG)

**Comment by insin** [comment]
Could you provide a sample of the status XML for a video you're seeing this happening with?

Should be http://localhost:8080/requests/status.xml on the machine VLC is running on.

**Comment by DictationScratchPad** [comment]
> Could you provide a sample of the status XML for a video you're seeing this happening with?
> 
> Should be http://localhost:8080/requests/status.xml on the machine VLC is running on.

As requested:

[status.txt](https://github.com/insin/vlc_remote/files/4950068/status.txt)

**Comment by insin** [comment]
TIL VLC translates type codes in its API responses, so we'll have to change how we look for subtitle and audio tracks:

```xml
<category name='Stream 2'>
  <info name='Type'>Undertekst</info>
  <info name='Codec'>Text subtitles with various tags (subt)</info>
</category>
```

**Comment by insin** [comment]
The sample you gave didn't have any Language info on the subtitle track, so I'll need to make subtitle track checking more lenient than it currently is too.
