### ISSUE TITLE
Show password (eye icon). Nonintuitive functionality.

### ISSUE THREAD

**Issue by JohnGurin** [insin/vlc_remote#7]
It shows the password when you hold the touch on the icon.
It would be more convenient that the icon switches the password visibility. So it would be easier to enter a password.

**Comment by insin** [comment]
For the "good first issue" tag, this needs to be changed to toggle `showPassword` using [`onTap`](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html#onTap) instead:

https://github.com/insin/vlc_remote/blob/240549ccfa798eabec467fa7c0d896433eaefb2b/lib/settings_screen.dart#L239-L248

**Comment by insin** [comment]
Fixed in #10
